apiVersion: v1
kind: Pod
metadata:
  name: curl-hey-pod
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  nodeSelector:
    kubernetes.io/hostname: "k8smaster.example.net"
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c"]
    args:
      - apt update && apt install -y curl && apt install -y hey && sleep infinity
